{% set pyproject = load_file_data("../pyproject.toml", from_recipe_dir=True)  %}
{% set versioneer = pyproject['tool']['versioneer'] %}
{% set python_version = pyproject['project']['requires-python'] %}
{% set setup_data = load_setup_py_data() %}

package:
  name: dms-datastore
  version: {{ setup_data['version'] }}

source:
  path: ..

build:
  # If the installation is complex, or different between Unix and Windows, use
  # separate bld.bat and build.sh files instead of this key.  Add the line
  # "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or
  # "skip: True  # [not win]" to limit to Windows.
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .
  noarch: python
  entry_points:
  {% for entry in setup_data['entry_points']['console_scripts'] %}
    - {{ entry }}
  {% endfor %}
  #skip:           true


requirements:
  # if you need compilers, uncomment these
  #    read more at https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html
  build:
    - python {{ python_version }}
    - setuptools
    {% for dep in pyproject['build-system']['requires'] %}
    - {{ dep.lower() }}
    {% endfor %}
  host:
    - python {{ python_version }}
    - pip
    - setuptools
    - versioneer
  run:
    - python {{ python_version }}
    # dependencies are defined in setup.py
    {% for dep in pyproject['project']['dependencies'] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
  commands:
    - pytest

about:
  home: https://github.com/CADWRDeltaModeling/dms_datastore
  summary: Downloading tools and data repository management
  license: {{ setup_data['license'] }}
