{% set pyproject = load_file_data("../pyproject.toml", from_recipe_dir=True)  %}
{% set python_version = pyproject['project']['requires-python'] %}
{% set setup_data = load_setup_py_data() %}

package:
  name: dms-datastore
  # Use the environment variable passed from the shell
  # Set via: export PKG_VERSION=$(python -m setuptools_scm)
  version: {{ environ.get('PKG_VERSION') }}

source:
  path: ..

build:
  # If the installation is complex, or different between Unix and Windows, use
  # separate bld.bat and build.sh files instead of this key.  Add the line
  # "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or
  # "skip: True  # [not win]" to limit to Windows.
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .
  noarch: python
  number: 0
  entry_points:
    {% for name, reference in pyproject['project']['scripts'].items() %}
    - {{ name }} = {{ reference }}
    {% endfor %}
  #skip:           true


requirements:
  # if you need compilers, uncomment these
  #    read more at https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html
  build:
    - python {{ pyproject['project']['requires-python'] }}
    - setuptools
    - setuptools-scm
    {% for dep in pyproject['build-system']['requires'] %}
    - {{ dep.lower() }}
    {% endfor %}
  host:
    - python {{ pyproject['project']['requires-python'] }}
    - pip
    {% for dep in pyproject['build-system']['requires'] %}
    - {{ dep.lower() }}
    {% endfor %}
    - setuptools
    - setuptools-scm
  run:
    - python {{ pyproject['project']['requires-python'] }}
    # dependencies are defined in pyproject.toml
    {% for dep in pyproject['project'].get('dependencies', []) %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
  commands:
    - (cd tests && pytest) # [win]
    - (cd tests; pytest) # [unix]

about:
  home: https://github.com/CADWRDeltaModeling/dms_datastore
  summary: Downloading tools and data repository management
  license: MIT
  license_file: LICENSE

